name: Deploy Frontend

on:
  push:
    branches:
      -main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Build del proyecto
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Limpiar carpeta (sin borrar .htaccess)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            find /var/www/ds1/cleanvalle -mindepth 1 ! -name '.htaccess' -exec rm -rf {} +

      - name: Desplegar al VPS vía SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "dist/*"
          target: "/var/www/ds1/cleanvalle"
          strip_components: 1
          rm: false

      - name: Configurar rutas de la SPA
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            printf '%s\n' \
              'Options -MultiViews' \
              '<IfModule mod_rewrite.c>' \
              '  RewriteEngine On' \
              '  RewriteBase /' \
              '  RewriteCond %{REQUEST_FILENAME} -f [OR]' \
              '  RewriteCond %{REQUEST_FILENAME} -d' \
              '  RewriteRule ^ - [L]' \
              '  RewriteRule ^ index.html [L]' \
              '</IfModule>' \
              > /var/www/ds1/cleanvalle/.htaccess
